# softmax 回归从零开始实现



In [2]:
# 导包

%matplotlib inline
import d2lzh as d2l
from mxnet import autograd,nd


In [ ]:
# 读取数据集

## 使用Fashion-MNIST数据集,并设置批量大小为256
batch_size = 256
train_iter,test_iter = d2l.load_data_fashion_mnist(batch_size=batch_size)


In [ ]:
# 初始化模型参数

## 已知每个样本输入是高和宽均为28像素的图像
## 模型的输入向量的长度是28x28=784:该向量的每个元素对应图像中每个像素
## softmax回归的权重和偏差参数分别为784x10和1x10的矩阵
num_inputs = 784
num_outputs = 10

W = nd.random.normal(scale=0.01,shape=(num_inputs,num_outputs))
b = nd.zeros(num_outputs)

W.attach_grad()
b.attach_grad()


In [6]:
# 实现softmax运算

X = nd.array([[1,2,3],[4,5,6]])
X.sum(axis=0,keepdims=True),X.sum(axis=1,keepdims=True)

def softmax(X):
    X_exp = X.exp()
    partitioin = X_exp.sum(axis=1,keepdims=True)
    return X_exp / partitioin # 这里应用了广播机制
    
## 对于随机输入,将每个元素变成了非负数,且每行和为1
X = nd.random.normal(shape=(2,5))
print(X)
X_prob = softmax(X)
X_prob,X_prob.sum(axis=1)



[[ 1.8307649  -1.1468065   0.05383795 -2.5074806  -0.59164983]
 [ 0.8586049  -0.22794184  0.20131476  0.35005474  0.5360521 ]]
<NDArray 2x5 @cpu(0)>


(
 [[0.7565211  0.03851929 0.12797098 0.00987973 0.06710884]
  [0.3143371  0.10605092 0.16290642 0.18903191 0.22767363]]
 <NDArray 2x5 @cpu(0)>,
 
 [0.99999994 1.        ]
 <NDArray 2 @cpu(0)>)

In [7]:
# 定义模型

def net(X):
    return softmax(nd.dot(X.reshape((-1,num_inputs)),W) + b)


In [9]:
# 定义损失函数 : 交叉熵损失函数

y_hat = nd.array([[0.1,0.3,0.6],[0.3,0.3,0.5]])
y = nd.array([0,2],dtype='int32')
nd.pick(y_hat,y)

def cross_entropy(y_hat,y):
    return -nd.pick(y_hat,y).log()



In [11]:
# 计算分类准确性

## 给定一个类别的预测概率分布y_hat,把预测概率最大的类别作为输出类别.如果它与真实类别y一致,说明这次预测是正确的
## 分类准确率 = 正确预测数量/总预测数量

def accuracy(y_hat,y):
    return (y_hat.argmax(axis=1) == y.astype('float32')).mean().asscalar()

accuracy(y_hat,y)

## 评价模型net在数据集data_iter上的准确率

def evaluate_accuracy(data_iter,net):
    acc_sum,n = 0.0,0
    for X,y in data_iter:
        y = y.astype('float32')
        acc_sum += (net(X).argmax(axis=1) == y).sum().asscalar()
        n += y.size
    return acc_sum / n

evaluate_accuracy(test_iter,net)
        


NameError: name 'test_iter' is not defined