In [1]:
# 创建NDArray

from mxnet import nd

x = nd.arange(12)
print(x)

x.shape
x.size
X = x.reshape((3,4))
nd.zeros((2,3,4))
Y = nd.ones((3,4))
nd.random.normal(0,1,shape=(3,4))



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>



[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [2]:
# 运算
X+Y
X-Y
X*Y
X/Y
# 指数运算
Y.exp()
nd.dot(X,Y.T)
# concatenate 连结
nd.concat(X,Y,dim=0),nd.concat(X,Y,dim=1)

X == Y
X.sum()
X.norm().asscalar()


22.494442

In [30]:
# 广播机制
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

A+B



[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [36]:
# 索引
# 左开右闭
X[1:3]
# 赋值
X[1,2]=9
X[1:2,:]=12
X




[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [41]:
# 自动求梯度
from mxnet import autograd,nd

x = nd.arange(4).reshape((4,1))
x

# attach_grad():申请梯度所需要的内存
x.attach_grad()
# record:要求MXNet记录与求梯度有关的计算
with autograd.record():
    y = 2 * nd.dot(x.T,x)
y.backward()
# 验证:2*x*x的梯度是4x
assert(x.grad - 4 * x).norm().asscalar() == 0
x.grad



[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [42]:
# 训练模式和预测模式
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())



False
True


In [ ]:
# 对Python控制流求梯度
